version: '3.5'
services:
  yolov4-sort:
    container_name: yolov4-sort
    hostname: yolov4-sort
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: yolov4-sort
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
